## Python Libraries for Data Analysis

#### Many popular Python toolboxes/libraries:

- Numpy
- SciPy
- Pandas
- SciKit-Learn

#### Visualization libraries:

- Matplotlib
- Seaborn
- Plotly

## Numpy (Numerical Python)

MultiDimensional Array

In [121]:
import numpy as np
data = np.random.randn(3,2)
data

array([[ 0.17832893, -1.4724583 ],
       [ 0.48690889, -1.92343116],
       [ 0.82745255, -0.43229894]])

In [122]:
data*10

array([[  1.78328933, -14.72458301],
       [  4.86908885, -19.23431164],
       [  8.27452548,  -4.32298937]])

In [123]:
data+data

array([[ 0.35665787, -2.9449166 ],
       [ 0.97381777, -3.84686233],
       [ 1.6549051 , -0.86459787]])

In [124]:
data

array([[ 0.17832893, -1.4724583 ],
       [ 0.48690889, -1.92343116],
       [ 0.82745255, -0.43229894]])

In [125]:
arr = np.array([[1,2,3],[4,5,6]])

In [126]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [127]:
arr2 = 1/arr
arr2

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [128]:
arr2>arr

array([[False, False, False],
       [False, False, False]])

In [129]:
arr = np.arange(10)

In [130]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
arr[5]

5

In [132]:
arr[3:5] = 23

In [133]:
arr

array([ 0,  1,  2, 23, 23,  5,  6,  7,  8,  9])

In [134]:
arr_slice = arr[3:5]

In [135]:
arr_slice

array([23, 23])

In [136]:
arr_slice[1] = 45678

In [137]:
arr

array([    0,     1,     2,    23, 45678,     5,     6,     7,     8,
           9])

In [138]:
arr

array([    0,     1,     2,    23, 45678,     5,     6,     7,     8,
           9])

In [139]:
arr_slice[:] = 64

In [146]:
arr_slice

array([64, 64])

In [147]:
arr[1:6]

array([ 1,  2, 64, 64,  5])

In [148]:
arr

array([ 0,  1,  2, 64, 64,  5,  6,  7,  8,  9])

In [149]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [150]:
arr2d[:2,0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [151]:
arr2d[1,:2]

array([4, 5])

In [152]:
arr2d[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
arr2d[:2,1:] = 0
arr2d


array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [154]:
arr2d[[0,2]]

array([[1, 0, 0],
       [7, 8, 9]])

In [155]:
arr2d[:,[0,2]]

array([[1, 0],
       [4, 0],
       [7, 9]])

In [226]:
names = np.array(["Bob", "theBuilder", "Karke", "Dhikayenge", "Bob", "theBuilder", "Hahioiha"])
data = np.random.randn(7,4)
names

array(['Bob', 'theBuilder', 'Karke', 'Dhikayenge', 'Bob', 'theBuilder',
       'Hahioiha'], dtype='<U10')

In [227]:
data

array([[ 1.43887728,  0.11803851,  1.73400581, -0.12186207],
       [-1.29685545, -0.73499885,  0.46023786,  1.12467197],
       [-0.09202691,  0.63463544, -0.15307788,  0.06624529],
       [-1.106472  ,  0.65193413,  0.3166987 ,  0.8046359 ],
       [ 0.82408439, -0.41450025,  0.76106987, -0.40424691],
       [ 0.30054532, -1.18925231, -2.39966593, -0.38893355],
       [-1.36474094,  0.70452819,  0.81373739,  1.17182634]])

In [228]:
names == "Bob"

array([ True, False, False, False,  True, False, False])

In [229]:
data[names=="Bob"]

array([[ 1.43887728,  0.11803851,  1.73400581, -0.12186207],
       [ 0.82408439, -0.41450025,  0.76106987, -0.40424691]])

In [230]:
data[names == "Bob",3]

array([-0.12186207, -0.40424691])

In [231]:
data[names == "Bob",2:]

array([[ 1.73400581, -0.12186207],
       [ 0.76106987, -0.40424691]])

In [232]:
mask = (names=="Bob") | (names == "theBuilder")

In [233]:
mask

array([ True,  True, False, False,  True,  True, False])

In [234]:
data[mask]

array([[ 1.43887728,  0.11803851,  1.73400581, -0.12186207],
       [-1.29685545, -0.73499885,  0.46023786,  1.12467197],
       [ 0.82408439, -0.41450025,  0.76106987, -0.40424691],
       [ 0.30054532, -1.18925231, -2.39966593, -0.38893355]])

In [235]:
data[names!="theBuilder"]=7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-1.29685545, -0.73499885,  0.46023786,  1.12467197],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.30054532, -1.18925231, -2.39966593, -0.38893355],
       [ 7.        ,  7.        ,  7.        ,  7.        ]])

In [239]:
arr = np.empty((8,4))
arr

array([[5.56344211e-263, 5.11796865e-307, 8.49032201e-268,
        8.90089299e-307],
       [2.01160975e-309, 1.10198930e+200, 9.44225010e-247,
        1.66139754e+151],
       [5.10696507e+160, 5.29879637e+180, 5.59939374e+072,
        1.01907704e+277],
       [4.69418760e+257, 9.03229333e+227, 5.52875806e+180,
        2.31285702e-191],
       [2.06999315e+161, 1.23968864e+224, 5.55603543e+180,
        5.81846707e+180],
       [4.98114114e+127, 1.30602960e+257, 6.76684424e+226,
        1.10168277e+169],
       [5.12622858e-266, 2.51968629e+180, 1.19267266e-275,
        7.82429653e-271],
       [1.14323352e+243, 2.25212130e+161, 2.52705624e-297,
        1.33360329e+241]])

In [240]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [242]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [243]:
arr[[-3,-4,-6]]

array([[5., 5., 5., 5.],
       [4., 4., 4., 4.],
       [2., 2., 2., 2.]])

In [250]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [247]:
arr[[1,5,7,2],[0,3,2,1]]

array([ 4, 23, 30,  9])

In [251]:
arr[[1,5,7,2]][:,[0,3,2,1]]

array([[ 4,  7,  6,  5],
       [20, 23, 22, 21],
       [28, 31, 30, 29],
       [ 8, 11, 10,  9]])

In [252]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [257]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [256]:
np.dot(arr.T,arr)

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [260]:
arr1 = np.arange(16).reshape((2,2,4))  # (no. of matrix, rows,columns)
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [255]:
arr.ravel() # multi to single array conversion

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [267]:
arr1.transpose((2,0,1)) # 2,2,4 --> m,r,c --> 2,0,1 --> 4,2,2 --> m,r,c

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [269]:
arr1.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [263]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [264]:
arr1.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])